version: "3"
services:
  sr:
    image: 'aftersound/weave:bundle'
    ports:
      - '8085:8080'
    environment:
      - APPLICATION=service.sr
  basics:
    image: 'aftersound/weave:bundle'
    ports:
      - '8080:8080'
    environment:
      - APPLICATION=service.basics
    depends_on:
      - sr