version: "3"
services:
  _sr:
    image: 'aftersound/weave:bundle'
    container_name: "sr0"
    ports:
      - '8085:8080'
    environment:
      - APPLICATION=service._sr
    networks:
      - weave_network
  _basics:
    image: 'aftersound/weave:bundle'
    container_name: "basics0"
    ports:
      - '8080:8080'
    environment:
      - APPLICATION=service._basics
    depends_on:
      - _sr
    networks:
      - weave_network
networks:
  weave_network: