version: "3"
services:
  _sr:
    image: 'aftersound/weave:bundle'
    container_name: "sr0"
    ports:
      - '8085:8080'
    environment:
      - APPLICATION=service._sr
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/discovery/service", "-H", "'Content-Type: application/json'", "-H", "'Accept: application/json'" ]
      interval: 3s
      timeout: 1s
      retries: 5
  _basics:
    image: 'aftersound/weave:bundle'
    container_name: "basics0"
    ports:
      - '8080:8080'
    environment:
      - APPLICATION=service._basics
    depends_on:
      _sr:
        condition: service_healthy
    restart: on-failure