CREATE TABLE EXTENSION_INFO( _group VARCHAR(255), name VARCHAR(255), version VARCHAR(255), base_type VARCHAR(1024) NOT NULL, type VARCHAR(1024) NOT NULL, jar_location VARCHAR(1024) NOT NULL, PRIMARY KEY (_group, name, version));

INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','Count','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.CountComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-common-extensions/0.0.1-SNAPSHOT/beam-common-extensions-0.0.1-SNAPSHOT.jar');
INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','Create','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.CreateComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-common-extensions/0.0.1-SNAPSHOT/beam-common-extensions-0.0.1-SNAPSHOT.jar');
INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','FlatMap','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.FlatMapComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-common-extensions/0.0.1-SNAPSHOT/beam-common-extensions-0.0.1-SNAPSHOT.jar');
INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','Function','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.FunctionComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-common-extensions/0.0.1-SNAPSHOT/beam-common-extensions-0.0.1-SNAPSHOT.jar');
INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','Map','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.MapComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-common-extensions/0.0.1-SNAPSHOT/beam-common-extensions-0.0.1-SNAPSHOT.jar');
INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','TextIO.read','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.TextIOReadComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-common-extensions/0.0.1-SNAPSHOT/beam-common-extensions-0.0.1-SNAPSHOT.jar');
INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','TextIO.write','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.TextIOWriteComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-common-extensions/0.0.1-SNAPSHOT/beam-common-extensions-0.0.1-SNAPSHOT.jar');
INSERT INTO EXTENSION_INFO VALUES('BEAM_PIPELINE_COMPOSER','MinimalWordCount','0.0.1-SNAPSHOT','io.aftersound.weave.beam.PipelineComposer','io.aftersound.weave.beam.MinimalWordCountPipelineComposer','file:///home/xuxiaochun/.m2/repository/io/aftersound/weave/beam-customized-extensions-test/0.0.1-SNAPSHOT/beam-customized-extensions-test-0.0.1-SNAPSHOT.jar');